### PR TITLE
Update ModCore to .net core 3

### LINKED ISSUE #80: Update to .Net Core 3.0
it's here boys

might do it myself, if you're lucky you might be faster

### PR DESCRIPTION
**Pull request by kashifsoofi**
Fixes #80

### CODE REVIEW

**Comment by Naamloos** [comment]
Does this build?

**Comment by Naamloos** [comment]
This pull request will be marked invalid until further notice from the author

**Comment by kashifsoofi** [comment]
Apologies, its building successfully, can commit nuget.config if needed.

**Comment by kashifsoofi** [comment]
Actually, the other PR done by Izumemori related is better, closing this one.

**Comment by li223** [comment]
F

**Comment by Naamloos** [comment]
Thank you for your collaboration, I will remove the invalid tag from the PR to make it count towards your hacktober progress

**Comment by kashifsoofi** [comment]
> 
> 
> Thank you for your collaboration, I will remove the invalid tag from the PR to make it count towards your hacktober progress

Thank you.

**Pull request closed without merging**
